#Demonstração NumPY 
**Disciplina - Introdução a Ciência de Dados - Univesp**

###Videoaula 5
###Prof. Dr. José Eduardo Santarem Segundo
**Aluno: Aelso Rocha Brito**
##**notebook**ComAnotaçõesDaVideoaula 

#Importar Biblioteca

In [1]:
import numpy as np

#Gerar Dados Aleatórios

##Gerar um NDArray de 2x3 (duas lista com 3 elementos)

In [2]:
dados=np.random.rand(2,3)

**Random** Valores aleatórios em uma determinada forma.

In [3]:
dados

array([[0.68637095, 0.45342431, 0.85055114],
       [0.25763941, 0.94306541, 0.15843829]])

#Tipo do Array

In [4]:
dados.dtype

dtype('float64')

Data type objects **(dtype)** descreve como os bytes no bloco de memória de tamanho fixo correspondente a um item da matriz devem ser interpretados. 

#Tamanho e quantidade de dimensões

In [5]:
dados.shape

(2, 3)

As variável **dados** é Array(Matrizes) de 2 linhas  e 3 colunas

In [6]:
dados.ndim

2

**ndmim** mostrar quantas dimensões(linhas) a varivável possuir. Nesse caso possuir 2 dimensões.

#Criar ndarray usando a função array
##Ao criar o array a função array tenta utilizar o melhor tipo de dado

In [7]:
lista=[1,2,5,7.8,1.25]

In [8]:
dados2=np.array(lista)

In [9]:
dados2

array([1.  , 2.  , 5.  , 7.8 , 1.25])

na váriavel lista tem valores inteiros**(int)**[1,2,3] e valores de Número real ou ponto flutuante**(float)**[7.8,1.25). Obs: Aplicações desenvolvida por empresa(s) norte americana(s) ou para eles. Fazem uso Ponto**(.)** ao invés de Vírgula**(,)** para separação de números.

In [10]:
lista2=[[1,2,3,4],[4,3,2,1]]

In [11]:
dados3=np.array(lista2)

In [12]:
dados3

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

#Outras maneiras de criar arrays

In [13]:
dadoszero=np.zeros(10)

Criar array com quantidade indicada(10) de zeros

In [14]:
dadoszero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
dadoszero2=np.zeros((2,3))

In [16]:
dadoszero2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
dadosum=np.ones(5)

Criar array com quantidade indicada(5) de uns

In [18]:
dadosum

array([1., 1., 1., 1., 1.])

In [19]:
dadosseq=np.arange(10)

A função **arange** criar um sequencia de numeros indicada nesse caso(10).
lembrado que começa pelo valor **0**.

In [20]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
dadosseq2=np.arange(0,20,2)

dadosseq2 a função arange temos (valor1,valor2,valor3), onde valor1 indica qual valor a array começa, o valor2 indica o valor final e valor3 indicar como vai ser a progressão. Então os dadoseq2 começa com valor 0 indo até o valor 20 de 2 em 2.

In [22]:
dadosseq2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Abaixo identificamos o tipo de dados(inteiro) e depois convertemos para float.

In [23]:
dadosseq.dtype

dtype('int64')

In [24]:
dadosseqf=dadosseq.astype(np.float64)

In [25]:
dadosseqf

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
dadosseqf.dtype

dtype('float64')

#Aritmética com Arrays

In [27]:
dados4=np.array([[1,2,3],[4,5,6]])

In [28]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

Multiplicação de Array

In [29]:
dados4*dados4

array([[ 1,  4,  9],
       [16, 25, 36]])

**Obs**>> Aqui estamos fazendo somente a operação. não estamos fazendo alteração(guardando) os valores do array 4

**Subtração**

In [30]:
dados4-dados4

array([[0, 0, 0],
       [0, 0, 0]])

**Divisão**

In [31]:
1/dados4

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [32]:
dados5=dados4+dados4

Quando queremos guarda informações geradas pelas operações, criamos uma variavel para isso. nesse caso **dados5**.

In [33]:
dados5

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [34]:
dados4

array([[1, 2, 3],
       [4, 5, 6]])

**Operadores de Comparação**

|**Operador**	|            | **Significado**|
--------------|------------|----------------|
|**>**        |            |**maior que**   |

In [35]:
dados5>dados4

array([[ True,  True,  True],
       [ True,  True,  True]])

#Indexação

In [36]:
dadosseq

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
dadosseq[5]

5

## Diferente de uma lista python, um recorte (fatia) de um ndarray sofrerá broadcast - é como se fosse uma view de bando de dados. 
##Com conjuntos imensos de dados isso é uma grande vantagem em relação a performance

In [38]:
dadosseq[3:6]

array([3, 4, 5])

In [39]:
dadosseq[3:6]=20

Pega a posição inicial[3] até posição final[6]. **Obs** mostraram o valor final -1 ou seja nesse caso mostraram a posição 3 até a 5.

In [40]:
dadosseq

array([ 0,  1,  2, 20, 20, 20,  6,  7,  8,  9])

In [41]:
fatiadados=dadosseq[2:4]

In [42]:
fatiadados

array([ 2, 20])

Na expressão abaixo valor atribuir o valor 2000 na posição 1. substitindo o valor 20 por 2000.

In [43]:
fatiadados[1]=2000

In [44]:
fatiadados

array([   2, 2000])

In [45]:
dadosseq

array([   0,    1,    2, 2000,   20,   20,    6,    7,    8,    9])

No comando abaixo vamos atribuir **[ : ]** o valor 333 todas a posição da variável fatiado

In [46]:
fatiadados[:]=333

In [47]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#Copiar dados

In [48]:
fatia2=dadosseq[2:4].copy()

In [49]:
fatia2

array([333, 333])

In [50]:
fatia2[:]=111

In [51]:
fatia2

array([111, 111])

In [52]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

#Array com mais de uma dimensão

Abaixo 3 **listas** com 3 **valores** cada

In [53]:
dados6=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [54]:
dados6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Recuperando valores dos array's
   

|**00**	| **01**| **02**| 
|-------|-------|-------|
| 10    |  11   |  12   |
|-------|-------|-------|
| 20    | 21    | 22    |   
|-------|-------|-------|   


##Matriz é uma tabela organizada em linhas e colunas no formato m x n, onde m representa o número de linhas (horizontal) e n o número de colunas (vertical)

Qual o valor da **m[1]** e **n[2]**?

In [55]:
dados6[1,2]

6

#Máscaras

In [56]:
dadosseq

array([  0,   1, 333, 333,  20,  20,   6,   7,   8,   9])

A variável **mascara** vai varrer todo o array e comparar quais valores da varíavel **dadosseq** são menores(<) que 100.

In [57]:
mascara=(dadosseq<100)

|**Operador**	|            | **Significado**|
--------------|------------|----------------|
|**<**        |            |**menor que**   |

O resultado dessa operação retorna valores **booleanos**: **True**(verdadeiro) para menores que 100 ou **False** para maiores que 100.

In [58]:
mascara

array([ True,  True, False, False,  True,  True,  True,  True,  True,
        True])

Vamos **Substituir** todos os valores que são menores que **20** por **8888**.

In [59]:
dadosseq[dadosseq<20]=8888

In [60]:
dadosseq

array([8888, 8888,  333,  333,   20,   20, 8888, 8888, 8888, 8888])

#Transposição

Vamos criar uma matriz com **15** valores distribuido em 3 linhas com 5 colunas

In [61]:
dados7=np.arange(15).reshape((3,5))

In [62]:
dados7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

Vamos fazer fazer a transposição da matriz

In [63]:
dados7.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

#Multiplicação de Matrizes com Dots

**dot** comando para multiplicação da matriz

In [64]:
np.dot(dados7.T,dados7)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

###seno     = sin(x) Retorna o seno de x radianos.###
###cosseno  = cos(x) Retorna o cosseno de x radianos###
###Potência = pow Retorna x elevado à potência y###
###Raiz Quadrada= sqrt Retorna a raiz quadrada inteira do inteiro não negativo n.###


# Vejam que há muitas outras funções que podem ser exploradas como: sin, cos, power, mod, sqrt entre outros.