#Demonstração Pré-Processamento de Dados
###Disciplina - Introdução a Ciência de Dados - Univesp
###Videoaula 12
###Prof. Dr. José Eduardo Santarem Segundo
Aluno: Aelso Rocha Brito 
##notebookComAnotaçõesDaVideoaula

O pré-processamento é uma fase que antecede ao uso dos modelos
de machine learning que veremos adiante, entretanto para que ele
possa ser executado com clareza e também com assertividade é de
fundamental importância que se conheça o processo completo de um
projeto de DS

#Importar Bibliotecas

In [1]:
import pandas as pd

#Trabalhar com dados dos jogos de Tenis como exemplo.
### https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2021.csv

Download de base de dados da internet.
Criando dataframe com as informações dos jogos de tênis.

In [2]:
dados=pd.read_csv('https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2021.csv')

Mostrando as 5 primeiras(head(5)) linhas do dataframe.

In [3]:
dados.head(5)

tourney_id  tourney_name surface  draw_size tourney_level  tourney_date  \
0  2021-0499  Delray Beach    Hard         32             A      20210104   
1  2021-0499  Delray Beach    Hard         32             A      20210104   
2  2021-0499  Delray Beach    Hard         32             A      20210104   
3  2021-0499  Delray Beach    Hard         32             A      20210104   
4  2021-0499  Delray Beach    Hard         32             A      20210104   

   match_num  winner_id  winner_seed winner_entry  ... l_1stIn l_1stWon  \
0        300     128034          4.0          NaN  ...    33.0     20.0   
1        299     128034          4.0          NaN  ...    46.0     29.0   
2        298     200624          NaN          NaN  ...    35.0     25.0   
3        297     106328          NaN            Q  ...    45.0     34.0   
4        296     128034          4.0          NaN  ...    43.0     28.0   

   l_2ndWon l_SvGms  l_bpSaved  l_bpFaced  winner_rank winner_rank_points  \
0       9.0     9.0        1.0        5.0         35.0             1518.0   
1      13.0    11.0        3.0        5.0         35.0             1518.0   
2       7.0    10.0        2.0        6.0        119.0              566.0   
3      18.0    11.0        9.0       11.0        789.0               22.0   
4      10.0    10.0        7.0       10.0         35.0             1518.0   

  loser_rank loser_rank_points  
0      119.0             566.0  
1      789.0              22.0  
2       74.0             877.0  
3      101.0             733.0  
4      293.0             171.0  

[5 rows x 49 columns]

Imprima um resumo conciso de um DataFrame.

Este método imprime informações sobre um DataFrame incluindo o índice dtype e colunas, valores não nulos e uso de memória.

In [4]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2713 entries, 0 to 2712
Data columns (total 49 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   tourney_id          2713 non-null   object 
 1   tourney_name        2713 non-null   object 
 2   surface             2713 non-null   object 
 3   draw_size           2713 non-null   int64  
 4   tourney_level       2713 non-null   object 
 5   tourney_date        2713 non-null   int64  
 6   match_num           2713 non-null   int64  
 7   winner_id           2713 non-null   int64  
 8   winner_seed         1165 non-null   float64
 9   winner_entry        417 non-null    object 
 10  winner_name         2713 non-null   object 
 11  winner_hand         2711 non-null   object 
 12  winner_ht           2377 non-null   float64
 13  winner_ioc          2713 non-null   object 
 14  winner_age          2713 non-null   float64
 15  loser_id            2713 non-null   int64  
 16  loser_

Gerando estatísticas descritivas.

As estatísticas descritivas incluem aquelas que resumem a tendência central, a dispersão e a forma da distribuição de um conjunto de dados, excluindo os NaNvalores.

Analisa séries numéricas e de objetos, bem como DataFrameconjuntos de colunas de tipos de dados mistos. A saída irá variar dependendo do que é fornecido. Consulte as notas abaixo para obter mais detalhes

In [5]:
dados.describe(include='all')

tourney_id     tourney_name surface    draw_size tourney_level  \
count        2713             2713    2713  2713.000000          2713   
unique        106              106       3          NaN             5   
top      2021-580  Australian Open    Hard          NaN             A   
freq          127              127    1588          NaN          1563   
mean          NaN              NaN     NaN    63.043126           NaN   
std           NaN              NaN     NaN    41.364539           NaN   
min           NaN              NaN     NaN     2.000000           NaN   
25%           NaN              NaN     NaN    32.000000           NaN   
50%           NaN              NaN     NaN    64.000000           NaN   
75%           NaN              NaN     NaN   128.000000           NaN   
max           NaN              NaN     NaN   128.000000           NaN   

        tourney_date    match_num      winner_id  winner_seed winner_entry  \
count   2.713000e+03  2713.000000    2713.000000  1165.000000          417   
unique           NaN          NaN            NaN          NaN            6   
top              NaN          NaN            NaN          NaN            Q   
freq             NaN          NaN            NaN          NaN          234   
mean    2.021060e+07   244.805381  127592.228898     7.687554          NaN   
std     2.831369e+02    71.808171   34029.378730     7.133621          NaN   
min     2.021010e+07     1.000000  100644.000000     1.000000          NaN   
25%     2.021032e+07   228.000000  105575.000000     3.000000          NaN   
50%     2.021061e+07   276.000000  106432.000000     6.000000          NaN   
75%     2.021082e+07   289.000000  128034.000000    10.000000          NaN   
max     2.021113e+07   300.000000  210107.000000    32.000000          NaN   

        ...      l_1stIn     l_1stWon     l_2ndWon      l_SvGms    l_bpSaved  \
count   ...  2622.000000  2622.000000  2622.000000  2623.000000  2622.000000   
unique  ...          NaN          NaN          NaN          NaN          NaN   
top     ...          NaN          NaN          NaN          NaN          NaN   
freq    ...          NaN          NaN          NaN          NaN          NaN   
mean    ...    50.122426    33.333715    14.495805    12.424705     4.847445   
std     ...    19.086299    14.219474     6.863399     4.229535     3.256841   
min     ...     2.000000     0.000000     0.000000     0.000000     0.000000   
25%     ...    36.000000    23.000000    10.000000     9.000000     2.000000   
50%     ...    47.000000    31.000000    14.000000    11.000000     4.000000   
75%     ...    61.000000    42.000000    18.000000    15.000000     7.000000   
max     ...   165.000000   104.000000    48.000000    31.000000    27.000000   

          l_bpFaced  winner_rank winner_rank_points   loser_rank  \
count   2622.000000  2708.000000        2708.000000  2687.000000   
unique          NaN          NaN                NaN          NaN   
top             NaN          NaN                NaN          NaN   
freq            NaN          NaN                NaN          NaN   
mean       8.721205    70.690177        2205.403988   103.363603   
std        4.132543   102.995958        2456.725751   149.529936   
min        0.000000     1.000000           1.000000     1.000000   
25%        6.000000    20.000000         854.750000    37.000000   
50%        8.000000    47.000000        1328.000000    68.000000   
75%       11.000000    87.000000        2395.500000   112.000000   
max       38.000000  1758.000000       12113.000000  2146.000000   

       loser_rank_points  
count        2687.000000  
unique               NaN  
top                  NaN  
freq                 NaN  
mean         1388.985858  
std          1463.155590  
min             1.000000  
25%           706.000000  
50%           990.000000  
75%          1589.000000  
max         12113.000000  

[11 rows x 49 columns]

Detectando valores ausentes.

Retorna um objeto booleano de mesmo tamanho indicando se os valores são NA. Valores NA, como Nenhum ou numpy.NaN, são mapeados para valores verdadeiros. Todo o resto é mapeado para valores falsos. Caracteres como strings vazias ''ou numpy.infnão são considerados valores NA (a menos que você defina ).pandas.options.mode.use_inf_as_na = True

In [6]:
dados.isnull()

tourney_id  tourney_name  surface  draw_size  tourney_level  \
0          False         False    False      False          False   
1          False         False    False      False          False   
2          False         False    False      False          False   
3          False         False    False      False          False   
4          False         False    False      False          False   
...          ...           ...      ...        ...            ...   
2708       False         False    False      False          False   
2709       False         False    False      False          False   
2710       False         False    False      False          False   
2711       False         False    False      False          False   
2712       False         False    False      False          False   

      tourney_date  match_num  winner_id  winner_seed  winner_entry  ...  \
0            False      False      False        False          True  ...   
1            False      False      False        False          True  ...   
2            False      False      False         True          True  ...   
3            False      False      False         True         False  ...   
4            False      False      False        False          True  ...   
...            ...        ...        ...          ...           ...  ...   
2708         False      False      False         True          True  ...   
2709         False      False      False         True          True  ...   
2710         False      False      False         True          True  ...   
2711         False      False      False         True          True  ...   
2712         False      False      False         True          True  ...   

      l_1stIn  l_1stWon  l_2ndWon  l_SvGms  l_bpSaved  l_bpFaced  winner_rank  \
0       False     False     False    False      False      False        False   
1       False     False     False    False      False      False        False   
2       False     False     False    False      False      False        False   
3       False     False     False    False      False      False        False   
4       False     False     False    False      False      False        False   
...       ...       ...       ...      ...        ...        ...          ...   
2708    False     False     False    False      False      False        False   
2709    False     False     False    False      False      False        False   
2710    False     False     False    False      False      False        False   
2711    False     False     False    False      False      False        False   
2712    False     False     False    False      False      False        False   

      winner_rank_points  loser_rank  loser_rank_points  
0                  False       False              False  
1                  False       False              False  
2                  False       False              False  
3                  False       False              False  
4                  False       False              False  
...                  ...         ...                ...  
2708               False       False              False  
2709               False       False              False  
2710               False       False              False  
2711               False       False              False  
2712               False        True               True  

[2713 rows x 49 columns]

###Verificar valores nulos nas colunas. Somando os valores nulos de cada coluna.

In [7]:
dados.isnull().sum()

tourney_id               0
tourney_name             0
surface                  0
draw_size                0
tourney_level            0
tourney_date             0
match_num                0
winner_id                0
winner_seed           1548
winner_entry          2296
winner_name              0
winner_hand              2
winner_ht              336
winner_ioc               0
winner_age               0
loser_id                 0
loser_seed            2020
loser_entry           2078
loser_name               0
loser_hand               0
loser_ht               522
loser_ioc                0
loser_age                2
score                    0
best_of                  0
round                    0
minutes                 77
w_ace                   91
w_df                    91
w_svpt                  91
w_1stIn                 91
w_1stWon                91
w_2ndWon                91
w_SvGms                 90
w_bpSaved               91
w_bpFaced               91
l_ace                   91
l

###Verificar coluna "winner_entry", que tem muitos valores nulos e indica como o vencedor entrou no torneio

In [8]:
dados['winner_entry'].describe()

count     417
unique      6
top         Q
freq      234
Name: winner_entry, dtype: object

In [9]:
dados['winner_entry'].unique()

array([nan, 'Q', 'WC', 'Alt', 'PR', 'LL', 'SE'], dtype=object)

###Apagar todas as linhas que o atributo "loser_rank" é nulo, porque são poucas ocasiões e isso pode implicar erros nos resultados.

In [10]:
dados.dropna(subset=['loser_rank'], inplace=True)

In [11]:
dados

tourney_id                  tourney_name surface  \
0                           2021-0499                  Delray Beach    Hard   
1                           2021-0499                  Delray Beach    Hard   
2                           2021-0499                  Delray Beach    Hard   
3                           2021-0499                  Delray Beach    Hard   
4                           2021-0499                  Delray Beach    Hard   
...                               ...                           ...     ...   
2707  2021-M-DC-2021-WG2-M-THA-DEN-01  Davis Cup WG2 R1: THA vs DEN    Hard   
2708  2021-M-DC-2021-WG2-M-THA-DEN-01  Davis Cup WG2 R1: THA vs DEN    Hard   
2709  2021-M-DC-2021-WG2-M-THA-DEN-01  Davis Cup WG2 R1: THA vs DEN    Hard   
2710  2021-M-DC-2021-WG2-M-TUR-LAT-01  Davis Cup WG2 R1: TUR vs LAT    Hard   
2711  2021-M-DC-2021-WG2-M-TUR-LAT-01  Davis Cup WG2 R1: TUR vs LAT    Hard   

      draw_size tourney_level  tourney_date  match_num  winner_id  \
0            32             A      20210104        300     128034   
1            32             A      20210104        299     128034   
2            32             A      20210104        298     200624   
3            32             A      20210104        297     106328   
4            32             A      20210104        296     128034   
...         ...           ...           ...        ...        ...   
2707          4             D      20210917          2     200416   
2708          4             D      20210917          4     200416   
2709          4             D      20210917          5     208937   
2710          4             D      20210918          1     123795   
2711          4             D      20210918          2     117356   

      winner_seed winner_entry  ... l_1stIn l_1stWon  l_2ndWon l_SvGms  \
0             4.0          NaN  ...    33.0     20.0       9.0     9.0   
1             4.0          NaN  ...    46.0     29.0      13.0    11.0   
2             NaN          NaN  ...    35.0     25.0       7.0    10.0   
3             NaN            Q  ...    45.0     34.0      18.0    11.0   
4             4.0          NaN  ...    43.0     28.0      10.0    10.0   
...           ...          ...  ...     ...      ...       ...     ...   
2707          NaN          NaN  ...    57.0     38.0      15.0    14.0   
2708          NaN          NaN  ...    45.0     30.0      14.0    10.0   
2709          NaN          NaN  ...    43.0     24.0      13.0    10.0   
2710          NaN          NaN  ...    50.0     34.0      20.0    11.0   
2711          NaN          NaN  ...    21.0     16.0       7.0     8.0   

      l_bpSaved  l_bpFaced  winner_rank winner_rank_points loser_rank  \
0           1.0        5.0         35.0             1518.0      119.0   
1           3.0        5.0         35.0             1518.0      789.0   
2           2.0        6.0        119.0              566.0       74.0   
3           9.0       11.0        789.0               22.0      101.0   
4           7.0       10.0         35.0             1518.0      293.0   
...         ...        ...          ...                ...        ...   
2707        5.0       11.0        905.0               16.0     1136.0   
2708       10.0       13.0        905.0               16.0      767.0   
2709        5.0       11.0       1136.0                8.0     1546.0   
2710        6.0        9.0        170.0              427.0      671.0   
2711        2.0        7.0        176.0              408.0      196.0   

     loser_rank_points  
0                566.0  
1                 22.0  
2                877.0  
3                733.0  
4                171.0  
...                ...  
2707               8.0  
2708              27.0  
2709               2.0  
2710              38.0  
2711             359.0  

[2687 rows x 49 columns]

###Apagar colunas que todos os valores são nulos

In [12]:
dados.dropna(axis=1, how= 'all')

tourney_id                  tourney_name surface  \
0                           2021-0499                  Delray Beach    Hard   
1                           2021-0499                  Delray Beach    Hard   
2                           2021-0499                  Delray Beach    Hard   
3                           2021-0499                  Delray Beach    Hard   
4                           2021-0499                  Delray Beach    Hard   
...                               ...                           ...     ...   
2707  2021-M-DC-2021-WG2-M-THA-DEN-01  Davis Cup WG2 R1: THA vs DEN    Hard   
2708  2021-M-DC-2021-WG2-M-THA-DEN-01  Davis Cup WG2 R1: THA vs DEN    Hard   
2709  2021-M-DC-2021-WG2-M-THA-DEN-01  Davis Cup WG2 R1: THA vs DEN    Hard   
2710  2021-M-DC-2021-WG2-M-TUR-LAT-01  Davis Cup WG2 R1: TUR vs LAT    Hard   
2711  2021-M-DC-2021-WG2-M-TUR-LAT-01  Davis Cup WG2 R1: TUR vs LAT    Hard   

      draw_size tourney_level  tourney_date  match_num  winner_id  \
0            32             A      20210104        300     128034   
1            32             A      20210104        299     128034   
2            32             A      20210104        298     200624   
3            32             A      20210104        297     106328   
4            32             A      20210104        296     128034   
...         ...           ...           ...        ...        ...   
2707          4             D      20210917          2     200416   
2708          4             D      20210917          4     200416   
2709          4             D      20210917          5     208937   
2710          4             D      20210918          1     123795   
2711          4             D      20210918          2     117356   

      winner_seed winner_entry  ... l_1stIn l_1stWon  l_2ndWon l_SvGms  \
0             4.0          NaN  ...    33.0     20.0       9.0     9.0   
1             4.0          NaN  ...    46.0     29.0      13.0    11.0   
2             NaN          NaN  ...    35.0     25.0       7.0    10.0   
3             NaN            Q  ...    45.0     34.0      18.0    11.0   
4             4.0          NaN  ...    43.0     28.0      10.0    10.0   
...           ...          ...  ...     ...      ...       ...     ...   
2707          NaN          NaN  ...    57.0     38.0      15.0    14.0   
2708          NaN          NaN  ...    45.0     30.0      14.0    10.0   
2709          NaN          NaN  ...    43.0     24.0      13.0    10.0   
2710          NaN          NaN  ...    50.0     34.0      20.0    11.0   
2711          NaN          NaN  ...    21.0     16.0       7.0     8.0   

      l_bpSaved  l_bpFaced  winner_rank winner_rank_points loser_rank  \
0           1.0        5.0         35.0             1518.0      119.0   
1           3.0        5.0         35.0             1518.0      789.0   
2           2.0        6.0        119.0              566.0       74.0   
3           9.0       11.0        789.0               22.0      101.0   
4           7.0       10.0         35.0             1518.0      293.0   
...         ...        ...          ...                ...        ...   
2707        5.0       11.0        905.0               16.0     1136.0   
2708       10.0       13.0        905.0               16.0      767.0   
2709        5.0       11.0       1136.0                8.0     1546.0   
2710        6.0        9.0        170.0              427.0      671.0   
2711        2.0        7.0        176.0              408.0      196.0   

     loser_rank_points  
0                566.0  
1                 22.0  
2                877.0  
3                733.0  
4                171.0  
...                ...  
2707               8.0  
2708              27.0  
2709               2.0  
2710              38.0  
2711             359.0  

[2687 rows x 49 columns]

###Alterar valor dos dados nulos em uma coluna

In [13]:
dados['loser_entry'].unique()

array([nan, 'Q', 'WC', 'Alt', 'PR', 'LL', 'SE'], dtype=object)

In [14]:
dados['loser_entry'].fillna(value='X',inplace=True)

In [15]:
dados['loser_entry'].unique()

array(['X', 'Q', 'WC', 'Alt', 'PR', 'LL', 'SE'], dtype=object)

###Alterar mais de um atributo, com condições diferentes

In [16]:
dados['w_ace'].unique()

array([ 4.,  7.,  6.,  2.,  5.,  3., 22., 10.,  9., 13., 27.,  0.,  8.,
        1., 15., 12., nan, 11., 14., 23., 17., 16., 18., 41., 26., 19.,
       21., 30., 25., 20., 29., 32., 28., 24., 34., 36., 44., 33., 49.,
       31.])

In [17]:
dados['loser_ht'].unique()

array([196.  ,    nan, 188.  , 185.  , 193.  , 206.  , 198.  , 191.  ,
       208.  , 183.  , 180.  , 178.  , 175.  , 190.  , 181.  , 211.  ,
       203.  , 173.  , 170.  , 172.  ,   1.83])

Trecho de código abaixo vamos substituir os valores da coluna  w_ace = 0 pela média dos valores dessa coluna.

In [18]:
dados.fillna(value={'w_ace':0,'loser_ht':dados['loser_ht'].mean()},inplace=True)

In [19]:
dados['w_ace'].unique()

array([ 4.,  7.,  6.,  2.,  5.,  3., 22., 10.,  9., 13., 27.,  0.,  8.,
        1., 15., 12., 11., 14., 23., 17., 16., 18., 41., 26., 19., 21.,
       30., 25., 20., 29., 32., 28., 24., 34., 36., 44., 33., 49., 31.])

In [20]:
dados['loser_ht'].unique()

array([196.        , 186.90294145, 188.        , 185.        ,
       193.        , 206.        , 198.        , 191.        ,
       208.        , 183.        , 180.        , 178.        ,
       175.        , 190.        , 181.        , 211.        ,
       203.        , 173.        , 170.        , 172.        ,
         1.83      ])

###Usar o método ffill para projetar um dado para o registro seguinte

Sinônimo de DataFrame.fillna()com method='ffill'.
Devoluções
Series / DataFrame ou Nenhum
Objeto com valores ausentes preenchidos ou Nenhum se inplace=True.

Método ffill para projetar um dado para o registro seguinte, ou seja, eu pego um dado que está nulo. Pegar o dado do registro anterior e coloco nele. As vezes é um dados de uma série temporal.

Método ffill  vai substituir o valor NaN do ano 1984 e substituir pelo valor anterior(1983). o mesmo vai acontecer com valor de 1988.

In [21]:
dados['minutes'][1975:1990]

1981    128.0
1982     98.0
1983    119.0
1984      NaN
1985    141.0
1986     98.0
1987    127.0
1988      NaN
1989     98.0
1990     83.0
1991    135.0
1992     85.0
1993    140.0
1994    144.0
1995    131.0
Name: minutes, dtype: float64

In [22]:
dados['minutes'].fillna(method='ffill',inplace=True)

In [23]:
dados['minutes'][1975:1990]

1981    128.0
1982     98.0
1983    119.0
1984    119.0
1985    141.0
1986     98.0
1987    127.0
1988    127.0
1989     98.0
1990     83.0
1991    135.0
1992     85.0
1993    140.0
1994    144.0
1995    131.0
Name: minutes, dtype: float64

###Identificar duplicados

In [24]:
dados.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
2707    False
2708    False
2709    False
2710    False
2711    False
Length: 2687, dtype: bool

In [25]:
dados.duplicated().sum()

0

###Eliminar duplicados de uma coluna (nem sempre se quer realmente fazer isso, cuidado)

In [26]:
dados.drop_duplicates(subset=['tourney_name'],inplace=True)

In [27]:
dados['tourney_name'].head(10)

0               Delray Beach
27                   Antalya
58     Great Ocean Road Open
113        Murray River Open
168                  Atp Cup
198          Australian Open
325                  Cordoba
352                Singapore
379              Montpellier
406             Buenos Aires
Name: tourney_name, dtype: object

In [28]:
dados.describe()

draw_size  tourney_date   match_num      winner_id  winner_seed  \
count  102.000000  1.020000e+02  102.000000     102.000000    52.000000   
mean    30.274510  2.021074e+07  180.764706  133268.029412     3.461538   
std     31.737836  3.231568e+02  144.438083   38036.661836     4.543738   
min      2.000000  2.021010e+07    1.000000  100644.000000     1.000000   
25%      4.000000  2.021043e+07    1.000000  105559.250000     1.000000   
50%     32.000000  2.021081e+07  300.000000  123046.500000     2.000000   
75%     32.000000  2.021102e+07  300.000000  134770.000000     4.000000   
max    128.000000  2.021113e+07  300.000000  209867.000000    26.000000   

        winner_ht  winner_age      loser_id  loser_seed    loser_ht  ...  \
count   86.000000  102.000000     102.00000    32.00000  102.000000  ...   
mean   188.116279   26.451719  134004.77451     4.90625  188.205796  ...   
std      6.915317    5.086951   38346.36714     5.72690    5.841122  ...   
min    170.000000   18.206708  104291.00000     1.00000  170.000000  ...   
25%    183.500000   22.735797  105750.75000     2.00000  185.475735  ...   
50%    188.000000   25.017112  111815.00000     3.00000  186.902941  ...   
75%    193.000000   29.934292  144684.00000     5.25000  188.000000  ...   
max    206.000000   40.172485  208029.00000    29.00000  211.000000  ...   

          l_1stIn   l_1stWon   l_2ndWon    l_SvGms  l_bpSaved  l_bpFaced  \
count   98.000000  98.000000  98.000000  98.000000  98.000000  98.000000   
mean    47.183673  30.153061  12.357143  10.959184   4.357143   8.000000   
std     19.641292  12.929110   5.378939   2.970363   3.561680   4.538495   
min      2.000000   0.000000   2.000000   1.000000   0.000000   1.000000   
25%     35.250000  22.250000   8.250000   9.000000   2.000000   6.000000   
50%     45.000000  28.000000  12.500000  10.000000   4.000000   8.000000   
75%     57.750000  38.000000  15.750000  13.000000   6.000000  10.000000   
max    165.000000  90.000000  26.000000  17.000000  27.000000  38.000000   

       winner_rank  winner_rank_points   loser_rank  loser_rank_points  
count   101.000000          101.000000   102.000000         102.000000  
mean     84.910891         2954.524752   181.186275        1690.441176  
std     139.960001         3246.627936   296.130448        2301.942432  
min       1.000000            9.000000     1.000000           1.000000  
25%      10.000000          708.000000    28.000000         315.750000  
50%      32.000000         1718.000000    65.500000        1002.000000  
75%     113.000000         3440.000000   211.500000        1934.500000  
max    1083.000000        12113.000000  1921.000000       12113.000000  

[8 rows x 35 columns]

#Vamos ver como fazer um deslocamento
###Vamos importar os dados das ações da Apple
###https://finance.yahoo.com/quote/AAPL/history/

In [29]:
dados2=pd.read_csv("AAPL.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'AAPL.csv'

In [ ]:
dados2

In [ ]:
dados2['close_ontem']=dados2['Close'].shift(1)

In [ ]:
dados2

###Nova coluna com a porcentagem de alteração de um dia para o outro

In [ ]:
dados2['alteracao %']=((dados2['Close']/dados2['close_ontem'])-1)*100

In [ ]:
dados2.head(20)

In [ ]:
dados2.dropna(subset=['alteracao %'], inplace=True)

In [ ]:
dados2

In [ ]:
dados2.describe(include = 'all')

###Transformar dados categóricos (qualitativos) em dados numéricos

In [ ]:
dados=pd.read_csv('https://raw.githubusercontent.com/JeffSackmann/tennis_atp/master/atp_matches_2021.csv')

In [ ]:
dados['winner_ioc']

In [ ]:
dados['winner_ioc'].unique()

###Veja a documentação do scikit-learn sobre preprocessing!!!!

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
paises=dados['winner_ioc']

In [ ]:
paises

In [ ]:
lencoder = LabelEncoder()
paises_numeros = lencoder.fit_transform(paises)
paises_numeros

In [ ]:
paises.head(10)

In [ ]:
dados['paises_numeros']=paises_numeros

In [ ]:
dados